Add ability to manipulate element attributes
eprints/eprints3.4 pull request #239
Opened 2022-08-11 15:20 UTC by fatchild

### Adding the ability to make attributes and their values more configurable. 
`perl_lib/EPrints/XML.pm`
- If a config level routine is present use it to process element attributes

`lib/cfg.d/build_attributes.pl`
- An example which provides the ability to add, change and conditionally add attributes and their values

As is, this function will not be called and will therefore will not break any current repository which upgrades to a version containing this change.

2022-08-14 13:10 UTC, fatchild commented
`build_node_attributes`
- Config is now a list of hashes, allowing user to add more attribute changes using the push function. This will prevent overwriting the original config assignment.
- Config path is more meaningful `$c->{config_attrs}->{"<attribute key>"}->{"<attribute value>"}`
- Examples updated
- Space indentations replaced with tabs

2022-08-15 10:07 UTC, drn05r commented on lib/cfg.d/build_attributes.pl
> +		if ( defined $value_in && $value_in ne "" )
Use `EPrints::Utils::is_set( $value_in )` instead to be more consistent/concise.

2022-08-15 10:07 UTC, drn05r commented on perl_lib/EPrints/XML.pm
> +        }
Tabbing still looks a little off

2022-08-15 10:10 UTC, drn05r requested changes
Generally this looks OK.  I have not tested the functionality of this code but I cannot see why it would not work.  There are a couple of minor things that could be tidied up.  These are indicated in the single/multi line comments.

2022-08-16 13:04 UTC, fatchild commented
### Both files updated...

`perl_lib/EPrints/XML.pm`

- Tabbing issue

`lib/cfg.d/build_attributes.pl`

- Use of `EPrints::Utils::is_set(  )` in line 58 and 71

Test notes/files incoming.

2022-09-14 14:41 UTC, drn05r approved these changes

2022-09-14 14:42 UTC, merged